spring.application.name=API-GestaoBeneficiarios-PlanodeSaude

spring.datasource.url=jdbc:h2:mem:applicationdb
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

